
# [CVE-2022-48565](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-48565)

## Description

- `An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities.`

## Cvss Data

- **Access Vector**:
  - 
- **Base Score**:
  - 

## Scores

- **Exploitability Score**:
  - 
- **Impact Score**:
  - 
- **Base Severity**:
  - 

## Other Information

- **Publish Date**:
  - 2023-08-22 19:16:32
- **Vulnerability Status**:
  - Modified

## References

- **cve@mitre.org**: https://bugs.python.org/issue42051
- **cve@mitre.org**: https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html
- **cve@mitre.org**: https://lists.debian.org/debian-lts-announce/2023/10/msg00017.html
- **cve@mitre.org**: https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/AFHYAGWBFBNUGWU6XWKBHTCV5NH77MB7/
- **cve@mitre.org**: https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/BAYWJD576JUKLHCWKDLMJSUGTRDKPF3M/
- **cve@mitre.org**: https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/KZRZRJHWLZ7MOJNPQBWGJVXMVYDC5BRA/
- **cve@mitre.org**: https://security.netapp.com/advisory/ntap-20231006-0007/
