
# [CVE-2024-0654](https://github.com/bayuncao/vul-cve-4)

## Description

- `A vulnerability, which was classified as problematic, was found in DeepFaceLab pretrained DF.wf.288res.384.92.72.22. Affected is an unknown function of the file mainscripts/Util.py. The manipulation leads to deserialization. Local access is required to approach this attack. The exploit has been disclosed to the public and may be used. VDB-251382 is the identifier assigned to this vulnerability.`

## Cvss Data

- **Access Vector**:
  - LOCAL
- **Base Score**:
  - 4.3

## Scores

- **Exploitability Score**:
  - 3.1
- **Impact Score**:
  - 6.4
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2024-01-18 01:15:44
- **Vulnerability Status**:
  - Analyzed

## References

- **cna@vuldb.com**: https://github.com/bayuncao/vul-cve-4
- **cna@vuldb.com**: https://github.com/bayuncao/vul-cve-4/blob/main/picture/1071705290840_.pic_hd.jpg
- **cna@vuldb.com**: https://vuldb.com/?ctiid.251382
- **cna@vuldb.com**: https://vuldb.com/?id.251382
