
# [CVE-2019-1010142](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-1010142)

## Description

- `scapy 2.4.0 is affected by: Denial of Service. The impact is: infinite loop, resource consumption and program unresponsive. The component is: _RADIUSAttrPacketListField.getfield(self..). The attack vector is: over the network or in a pcap. both work.`

## Cvss Data

- **Access Vector**:
  - NETWORK
- **Base Score**:
  - 5.0

## Scores

- **Exploitability Score**:
  - 10.0
- **Impact Score**:
  - 2.9
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2019-07-19 16:15:12
- **Vulnerability Status**:
  - Modified

## References

- **josh@bress.net**: http://www.securityfocus.com/bid/106674
- **josh@bress.net**: https://github.com/secdev/scapy/pull/1409
- **josh@bress.net**: https://github.com/secdev/scapy/pull/1409/files#diff-441eff981e466959968111fc6314fe93L1058
- **josh@bress.net**: https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/42NRPMC3NS2QVFNIXYP6WV2T3LMLLY7E/
- **josh@bress.net**: https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/T46XW4S5BCA3VV3JT3C5Q6LBEXSIACLN/
- **josh@bress.net**: https://www.imperva.com/blog/scapy-sploit-python-network-tool-is-vulnerable-to-denial-of-service-dos-attack-cve-pending/
