
# [CVE-2019-16226](https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20memory%20corruption%20vuln)

## Description

- `An issue was discovered in py-lmdb 0.97. mdb_node_del does not validate a memmove in the case of an unexpected node->mn_hi, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.`

## Cvss Data

- **Access Vector**:
  - NETWORK
- **Base Score**:
  - 5.0

## Scores

- **Exploitability Score**:
  - 10.0
- **Impact Score**:
  - 2.9
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2019-09-11 15:15:11
- **Vulnerability Status**:
  - Analyzed

## References

- **cve@mitre.org**: https://github.com/TeamSeri0us/pocs/tree/master/lmdb/lmdb%20memory%20corruption%20vuln
