
# [CVE-2019-16249](https://bugzilla.redhat.com/show_bug.cgi?id=1752702)

## Description

- `OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.`

## Cvss Data

- **Access Vector**:
  - NETWORK
- **Base Score**:
  - 5.0

## Scores

- **Exploitability Score**:
  - 10.0
- **Impact Score**:
  - 2.9
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2019-09-11 23:15:14
- **Vulnerability Status**:
  - Analyzed

## References

- **nvd@nist.gov**: https://bugzilla.redhat.com/show_bug.cgi?id=1752702
- **cve@mitre.org**: https://github.com/opencv/opencv/issues/15481
