
# [CVE-2019-5010](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-5010)

## Description

- `An exploitable denial-of-service vulnerability exists in the X509 certificate parser of Python.org Python 2.7.11 / 3.6.6. A specially crafted X509 certificate can cause a NULL pointer dereference, resulting in a denial of service. An attacker can initiate or accept TLS connections using crafted certificates to trigger this vulnerability.`

## Cvss Data

- **Access Vector**:
  - NETWORK
- **Base Score**:
  - 5.0

## Scores

- **Exploitability Score**:
  - 10.0
- **Impact Score**:
  - 2.9
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2019-10-31 21:15:13
- **Vulnerability Status**:
  - Modified

## References

- **talos-cna@cisco.com**: http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html
- **talos-cna@cisco.com**: https://access.redhat.com/errata/RHSA-2019:3520
- **talos-cna@cisco.com**: https://access.redhat.com/errata/RHSA-2019:3725
- **talos-cna@cisco.com**: https://lists.apache.org/thread.html/r1b103833cb5bc8466e24ff0ecc5e75b45a705334ab6a444e64e840a0%40%3Cissues.bookkeeper.apache.org%3E
- **talos-cna@cisco.com**: https://lists.debian.org/debian-lts-announce/2020/07/msg00011.html
- **talos-cna@cisco.com**: https://lists.debian.org/debian-lts-announce/2020/08/msg00034.html
- **talos-cna@cisco.com**: https://security.gentoo.org/glsa/202003-26
- **talos-cna@cisco.com**: https://talosintelligence.com/vulnerability_reports/TALOS-2019-0758
