
# [CVE-2020-15523](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15523)

## Description

- `In Python 3.6 through 3.6.10, 3.7 through 3.7.8, 3.8 through 3.8.4rc1, and 3.9 through 3.9.0b4 on Windows, a Trojan horse python3.dll might be used in cases where CPython is embedded in a native application. This occurs because python3X.dll may use an invalid search path for python3.dll loading (after Py_SetPath has been used). NOTE: this issue CANNOT occur when using python.exe from a standard (non-embedded) Python installation on Windows.`

## Cvss Data

- **Access Vector**:
  - LOCAL
- **Base Score**:
  - 6.9

## Scores

- **Exploitability Score**:
  - 3.4
- **Impact Score**:
  - 10.0
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2020-07-04 23:15:10
- **Vulnerability Status**:
  - Analyzed

## References

- **cve@mitre.org**: https://bugs.python.org/issue29778
- **cve@mitre.org**: https://github.com/python/cpython/pull/21297
- **cve@mitre.org**: https://security.netapp.com/advisory/ntap-20210312-0004/
