
# [CVE-2020-15701](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15701)

## Description

- `An unhandled exception in check_ignored() in apport/report.py can be exploited by a local attacker to cause a denial of service. If the mtime attribute is a string value in apport-ignore.xml, it will trigger an unhandled exception, resulting in a crash. Fixed in 2.20.1-0ubuntu2.24, 2.20.9-0ubuntu7.16, 2.20.11-0ubuntu27.6.`

## Cvss Data

- **Access Vector**:
  - LOCAL
- **Base Score**:
  - 2.1

## Scores

- **Exploitability Score**:
  - 3.9
- **Impact Score**:
  - 2.9
- **Base Severity**:
  - LOW

## Other Information

- **Publish Date**:
  - 2020-08-06 23:15:11
- **Vulnerability Status**:
  - Analyzed

## References

- **security@ubuntu.com**: https://launchpad.net/bugs/1877023
- **security@ubuntu.com**: https://usn.ubuntu.com/4449-1
- **security@ubuntu.com**: https://usn.ubuntu.com/4449-1/
- **security@ubuntu.com**: https://usn.ubuntu.com/4449-2/
