
# [CVE-2023-26151](https://gist.github.com/artfire52/1540b234350795e0ecb4d672608dbec8)

## Description

- `Versions of the package asyncua before 0.9.96 are vulnerable to Denial of Service (DoS) such that an attacker can send a malformed packet and as a result, the server will enter into an infinite loop and consume excessive memory.`

## Cvss Data

- **Access Vector**:
  - 
- **Base Score**:
  - 

## Scores

- **Exploitability Score**:
  - 
- **Impact Score**:
  - 
- **Base Severity**:
  - 

## Other Information

- **Publish Date**:
  - 2023-10-03 05:15:50
- **Vulnerability Status**:
  - Modified

## References

- **report@snyk.io**: https://gist.github.com/artfire52/1540b234350795e0ecb4d672608dbec8
- **report@snyk.io**: https://github.com/FreeOpcUa/opcua-asyncio/commit/f6603daa34a93a658f0e176cb0b9ee5a6643b262
- **report@snyk.io**: https://github.com/FreeOpcUa/opcua-asyncio/issues/1013
- **report@snyk.io**: https://github.com/FreeOpcUa/opcua-asyncio/pull/1039
- **report@snyk.io**: https://github.com/FreeOpcUa/opcua-asyncio/releases/tag/v0.9.96
- **report@snyk.io**: https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673709
