
# [CVE-2013-4189](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4189)

## Description

- `Multiple unspecified vulnerabilities in (1) dataitems.py, (2) get.py, and (3) traverseName.py in Plone 2.1 through 4.1, 4.2.x through 4.2.5, and 4.3.x through 4.3.1 allow remote authenticated users with administrator access to a subtree to access nodes above the subtree via unknown vectors.`

## Cvss Data

- **Access Vector**:
  - NETWORK
- **Base Score**:
  - 6.5

## Scores

- **Exploitability Score**:
  - 8.0
- **Impact Score**:
  - 6.4
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2014-03-11 19:37:02
- **Vulnerability Status**:
  - Analyzed

## References

- **secalert@redhat.com**: http://plone.org/products/plone-hotfix/releases/20130618
- **secalert@redhat.com**: http://plone.org/products/plone/security/advisories/20130618-announcement
- **secalert@redhat.com**: http://seclists.org/oss-sec/2013/q3/261
- **secalert@redhat.com**: https://bugzilla.redhat.com/show_bug.cgi?id=978450
