
# [CVE-2019-14491](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14491)

## Description

- `An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service.`

## Cvss Data

- **Access Vector**:
  - NETWORK
- **Base Score**:
  - 6.4

## Scores

- **Exploitability Score**:
  - 10.0
- **Impact Score**:
  - 4.9
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2019-08-01 17:15:13
- **Vulnerability Status**:
  - Modified

## References

- **cve@mitre.org**: http://lists.opensuse.org/opensuse-security-announce/2019-12/msg00025.html
- **cve@mitre.org**: https://github.com/opencv/opencv/compare/33b765d...4a7ca5a
- **cve@mitre.org**: https://github.com/opencv/opencv/compare/371bba8...ddbd10c
- **cve@mitre.org**: https://github.com/opencv/opencv/issues/15125
- **cve@mitre.org**: https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HPFLN6QAX6SUA4XR4NMKKXX26H3TYCVQ/
