
# [CVE-2023-25399](http://www.square16.org/achievement/cve-2023-25399/)

## Description

- `A refcounting issue which leads to potential memory leak was discovered in scipy commit 8627df31ab in Py_FindObjects() function.`

## Cvss Data

- **Access Vector**:
  - 
- **Base Score**:
  - 

## Scores

- **Exploitability Score**:
  - 
- **Impact Score**:
  - 
- **Base Severity**:
  - 

## Other Information

- **Publish Date**:
  - 2023-07-05 17:15:09
- **Vulnerability Status**:
  - Analyzed

## References

- **cve@mitre.org**: http://www.square16.org/achievement/cve-2023-25399/
- **cve@mitre.org**: https://github.com/scipy/scipy/issues/16235
- **cve@mitre.org**: https://github.com/scipy/scipy/pull/16397
