
# [CVE-2021-32285](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-32285)

## Description

- `An issue was discovered in gravity through 0.8.1. A NULL pointer dereference exists in the function list_iterator_next() located in gravity_core.c. It allows an attacker to cause Denial of Service.`

## Cvss Data

- **Access Vector**:
  - NETWORK
- **Base Score**:
  - 4.3

## Scores

- **Exploitability Score**:
  - 8.6
- **Impact Score**:
  - 2.9
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2021-09-20 16:15:10
- **Vulnerability Status**:
  - Analyzed

## References

- **cve@mitre.org**: https://github.com/marcobambini/gravity/issues/319
