
# [CVE-2020-26244](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-26244)

## Description

- `Python oic is a Python OpenID Connect implementation. In Python oic before version 1.2.1, there are several related cryptographic issues affecting client implementations that use the library. The issues are: 1) The IdToken signature algorithm was not checked automatically, but only if the expected algorithm was passed in as a kwarg. 2) JWA `none` algorithm was allowed in all flows. 3) oic.consumer.Consumer.parse_authz returns an unverified IdToken. The verification of the token was left to the discretion of the implementator. 4) iat claim was not checked for sanity (i.e. it could be in the future). These issues are patched in version 1.2.1.`

## Cvss Data

- **Access Vector**:
  - NETWORK
- **Base Score**:
  - 4.9

## Scores

- **Exploitability Score**:
  - 6.8
- **Impact Score**:
  - 4.9
- **Base Severity**:
  - MEDIUM

## Other Information

- **Publish Date**:
  - 2020-12-02 20:15:13
- **Vulnerability Status**:
  - Analyzed

## References

- **security-advisories@github.com**: https://github.com/OpenIDC/pyoidc/commit/62f8d753fa17c8b1f29f8be639cf0b33afb02498
- **security-advisories@github.com**: https://github.com/OpenIDC/pyoidc/releases/tag/1.2.1
- **security-advisories@github.com**: https://github.com/OpenIDC/pyoidc/security/advisories/GHSA-4fjv-pmhg-3rfg
- **security-advisories@github.com**: https://pypi.org/project/oic/
